### ISSUE TITLE
vcf cannot be used for truvari

### ISSUE THREAD

**Issue by lok27395** [songbowang125/SVision-pro#11]
Hi author,

I just use this tool to call SV for trial on GIAB's benchmarking set. However, the vcf output is different from standard form in which the REF and ALT is replaced with N and SV/CSV. Although INFO states about details of mutation point, the output vcf cannot be used for truvari bench or bcftools stats for counting vcf amount etc.

Sample used: HG002_PacBio-HiFi-Revio_20231031_48x_CHM13v2.0.bam from GIAB (aligned hifi)

VCF output:

> #CHROM  POS     ID	REF     ALT     QUAL    FILTER  INFO    FORMAT  HG002_PacBio-HiFi-Revio_20231031_48x_CHM13v2.0.bam
chr1    36360   0	N	SV	.	PASS    END=36428;SVLEN=68;SVTYPE=DEL;SUPPORT=7;VAF=0.27;BKPS=DEL_68_chr1_36360_36428_36360;RNAMES=m84039_230928_213653_s3/44831346/ .......

bcftools stats: (only report as others types...)

> ...
SN	0	number of others:	23716
...

Or is my code wrong?

> SVision-pro --target_path ../HG002_PacBio-HiFi-Revio_20231031_48x_CHM13v2.0.bam --genome_path ../chm13v2.0.fa --model_path SVision-pro/src/pre_process/model_liteunet_256_8_16_32_32_32.pth --out_path svisionpro_out/ --sample_name HG002BCM --detect_mode germline --preset hifi

Thanks.

**Comment by songbowang125** [comment]
Did you use the SVision-pro version 2.0? Since everything went well with truvari before the version of 2.0. 

The version 2.0 outputs BNDs and BND records would cause some errors for truvari when I tested other tools such as Jasmine, perhaps due to the two unsorted genome positions of BNDs. 

Would you please try SVision-pro v2.0 with parameter --skip_bnd? Or, you can sent me your VCF file (to email songbowang125@163.com ) and I will locate the errors and fix them. 

Thanks a lot.

**Comment by lok27395** [comment]
> Did you use the SVision-pro version 2.0? Since everything went well with truvari before the version of 2.0.
> 
> The version 2.0 outputs BNDs and BND records would cause some errors for truvari when I tested other tools such as Jasmine, perhaps due to the two unsorted genome positions of BNDs.
> 
> Would you please try SVision-pro v2.0 with parameter --skip_bnd? Or, you can sent me your VCF file (to email [songbowang125@163.com](mailto:songbowang125@163.com) ) and I will locate the errors and fix them.
> 
> Thanks a lot.

Just sent the vcf FYR.

If I skip reporting BND, would I miss that complex SV in the VCF? or it just separately report as two simple SV?

Thanks

**Comment by songbowang125** [comment]
It will only skip BND records, and all the other records in vcf will be kept as same

**Comment by lok27395** [comment]
Dear Songbo,

Can you suggest which version's vcf output is currently acceptable by truvari?

Many thanks!

**Comment by songbowang125** [comment]
Hi, I have just tested the vcf file you sent to me and it goes well with truvari. My truvari version is v3.5.0. May I know your errors logs when running truvari?

**Comment by songbowang125** [comment]
I also tried the newest version (v2.0) of SVision-pro, and the BNDs were kept. All the parameters are default (only setting input/output, min_supp parameters). 

bcftools, bgzip and tabix were used for sorting, zipping and indexing.

The truvari (v3.5.0) command line: truvari bench -b xxx -c xxx --includedbed -r 1000 -p 0 -f xxx -o xxx --passonly

There was no errors and everything went fine. So, please let me know if you still have errors and sent me your error logs so that I can check that.

**Comment by lok27395** [comment]
Dear Songbo,

I tried the truvari you mentioned (v3.5) and it went well. My previously used version was the latest therefore it may not support the input I guess. The main error is truvari cannot parse the information.

Thanks for your support!

**Comment by songbowang125** [comment]
I tested the latest version of Truvari (v4.3.1) and met the error log: 'Permission denied: Unknown error 68416816'. This error happened with VCF files from all other callers I tested, such as cuteSV and sniffles2. 

Therefore, this is a error caused by Truvari but not callers. I found a potential solution for Truvari at https://github.com/ACEnglish/truvari/issues/229.

**Comment by lok27395** [comment]
issue fixed, able to run with latest truvari and svisonpro2.0; not sure why but it works unlike other callers.

thanks!

> I tested the latest version of Truvari (v4.3.1) and met the error log: 'Permission denied: Unknown error 68416816'. This error happened with VCF files from all other callers I tested, such as cuteSV and sniffles2.
> 
> Therefore, this is a error caused by Truvari but not callers. I found a potential solution for Truvari at [ACEnglish/truvari#229](https://github.com/ACEnglish/truvari/issues/229).
