### ISSUE TITLE
the number of somatic sv is a bit less

### ISSUE THREAD

**Issue by DayTimeMouse** [songbowang125/SVision-pro#14]
Hi,

I used SVision-pro to call somatic SVs, but the number of somatic SVs identified is relatively low, only around 500. In comparison, when using pbsv, the number is over 5000. Is it normal?

Best regards.

**Comment by songbowang125** [comment]
Thanks for using SVision-pro. 5000 somatics SVs seems a little too many. I think pbsv is not designed for somatic SV calling. Did you use pbsv and merging tools for somatic calling? If so, as we have showed in our paper, this would lead to many false-positive results. 

There are two ways to increase the somatic sv number for SVision-pro. Using lower min_supp, using larger image-size model (for detecting very low-frequency events), or adding parameter '--skip_mismatch_filter' (I will make this as a defalut one).

**Comment by DayTimeMouse** [comment]
Thanks to response!

Another question, after I run `python ../SVision-pro/extract_op.py --input_vcf tumor.svision_pro_v2.0.s3.vcf --extract somatic`, should I do filter the result? Because of the GT is 0/0 in tumor sample. Like：

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	tumor	normal
chr1	215350	10	N	SV	.	PASS	END=215416;SVLEN=66;SVTYPE=DEL;SUPPORT=3;VAF=0.05;BKPS=DEL_66_chr1_215350_215416_215350;BKPSIT=DEL_NewCOMP;RNAMES=m84072_240516_062357_s1/129108140/ccs,m84207_240818_035451_s2/67895338/ccs,m84072_240516_062357_s1/259986400/ccs	GT:DR:DV	0/0:60:3	0/0:NA:NA
```
Should `chr1	215350` be a  retained variant?

**Comment by songbowang125** [comment]
There is no need to perform other filters or postprocesses, but only the extract_op.py. 

The GT flag (e.g. 0/0, 0/1 and 1/1) are typically detemined by the variant allele frequency (VAF). For example, variants with VAF less than 0.2 would be considered as GT 0/0. Therefore, we think the GT flag is not applicable for tumor samples since there are so many low-frequent variants. And SVision-pro use its unique flags (the NewCOMP, NewAllele) for more accurate for somatic variant extraction.

**Comment by DayTimeMouse** [comment]
Thanks to response.

Another question: I chose pbmm2 as the aligner. Is it okay to do so?

**Comment by songbowang125** [comment]
Of course you can use pbmm2 for alignment. Pbmm2, minimap2 and ngmlr are tested ok with SVision-pro.
